data_index

esri_sources <- tibble::tribble(
  ~name, ~slug, ~url, ~source, ~source_url, ~esri_server,
  "Maryland Food Stores 2017-2018", "md_food_stores_2017_2018", "https://gis.mdfoodsystemmap.org/server/rest/services/FoodMapMD/MD_Food_Map_Services/MapServer/218/", "Maryland Food System Map", "https://data-clf.hub.arcgis.com/datasets/c4a2bd61eaac4425b3e2e9c40735a7ae_218", "MapServer",
  "Farmers Markets 2020", "farmers_markets_2020", "https://gis.mdfoodsystemmap.org/server/rest/services/FoodMapMD/MD_Food_Map_Services/MapServer/481/", "Maryland Food System Map", "https://data-clf.hub.arcgis.com/datasets/a62650c0ae6d46ecbe199108c1125019_239", "MapServer",
  "Baltimore City Food Stores 2016", "baltimore_food_stores_2016", "https://gis.mdfoodsystemmap.org/server/rest/services/FoodMapMD/MD_Food_Map_Services/MapServer/217/", "Maryland Food System Map", "https://data-clf.hub.arcgis.com/datasets/650fa48f80ae46ef9843171703ff96f0_217", "MapServer",
  "Completed City Demo", "baltimore_demolitions", "https://egisdata.baltimorecity.gov/egis/rest/services/Housing/DHCD_Open_Baltimore_Datasets/FeatureServer/0/", "Open Baltimore", "https://data.baltimorecity.gov/datasets/completed-city-demo", "FeatureServer",
  "Contour 2ft", "contour_2ft", "https://egisdata.baltimorecity.gov/egis/rest/services/Housing/dmxBoundaries/MapServer/26/", "Open Baltimore", "https://data.baltimorecity.gov/datasets/contour-2ft-1", "MapServer",
  "Contours 10ft", "contours_10ft", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Contours_10ft/FeatureServer/0/", "Open Baltimore", "https://data.baltimorecity.gov/datasets/contours-10ft-1", "FeatureServer",
  "Vacant Building Notices Open", "open_vacant_building_notices", "https://egisdata.baltimorecity.gov/egis/rest/services/Housing/DHCD_Open_Baltimore_Datasets/FeatureServer/1/", "Open Baltimore", "https://data.baltimorecity.gov/datasets/vacant-building-notices-open", "FeatureServer",
  "Liquor Licenses", "liquor_licenses", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Liquor_Licenses/FeatureServer/0/", "Open Baltimore", "https://data.baltimorecity.gov/datasets/liquor-licenses", "FeatureServer",
  "Fixed Speed Cameras", "fixed_speed_cameras", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Fixed_Speed_Cameras/FeatureServer/0/", "Open Baltimore", "https://data.baltimorecity.gov/datasets/fixed-speed-cameras", "FeatureServer",
  "Red Light Cameras", "red_light_cameras", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Red_Light_Cameras/FeatureServer/0/", "Open Baltimore", "https://data.baltimorecity.gov/datasets/red-light-cameras-1", "FeatureServer",
  "Edge of Pavement", "edge_of_pavement", "https://maps.baltimorecity.gov/egis/rest/services/OpenBaltimore/Edge_of_Pavement/MapServer/0/", NA, NA, "MapServer"
)

agencies <-
  c("Health", "Transportation", "Recreation & Parks", "Solid Waste", "Housing", "Water Wastewater", "Call Center", "Finance", "BGE", "Fire Department", "Parking Authority", "Public Works", "Mayor's Office", "Liquor Board", "BCIT", "General Services")

usethis::use_data(esri_sources, agencies, internal = TRUE, overwrite = TRUE)



data_index <- tibble::tribble(
  ~slug, ~name, ~filetype, ~location, ~documented, ~crs, ~data_year, ~date_updated, ~datetime_updated, ~data_coverage, ~license, ~layer_maintainer, ~layer_url, ~layer_info, ~public_url, ~description, ~notes, ~location_alt, ~frequency,
  "adopted_plans", "Adopted city plans, accepted community-initiated plans, and LINCS corridors", "rda", "data", TRUE, 2804L, NA, "2021-01-24", NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "baltimore_block_groups", "U.S. Census Block Groups in Baltimore City", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "baltimore_blocks", "U.S. Census Blocks (2010 Decennial) in Baltimore City", "rda", "data", TRUE, 2804L, 2010L, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "baltimore_city", "Generalized political boundary for Baltimore City", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "baltimore_city_detailed", "Detailed physical boundary for Baltimore City", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "baltimore_mihp", "Maryland Inventory of Historic Properties in Baltimore City", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "baltimore_msa_counties", "County boundaries for the Baltimore–Columbia–Towson MSA", "rda", "data", TRUE, 2804L, NA, "2021-01-14", NA, "Baltimore MSA", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "baltimore_msa_streets", NA, "gpkg", "cachedata", FALSE, 2804L, NA, NA, NA, "Baltimore MSA", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "baltimore_pumas", NA, "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "baltimore_tracts", "U.S. Census Tracts in Baltimore City", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "baltimore_water", "Baltimore Water", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "bcps_programs", "Baltimore City Public School Programs", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "bcps_zones", "Baltimore City Public Schools School Zones or School Attendance Zones", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "congressional_districts", "U.S. Congressional Districts for Baltimore City", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore area", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "council_districts", "Baltimore City Council Districts", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "csas", "Baltimore City Community Statistical Areas", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "edge_of_pavement", NA, "gpkg", "cachedata", FALSE, 2804L, 2017L, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "explore_baltimore", "Stories from Explore Baltimore Heritage", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore area", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "hmt_2017", "Housing Market Typology 2017", "rda", "data", TRUE, 2804L, NA, "2021-01-09", NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "legislative_districts", "Maryland Legislative Districts for Baltimore City", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore area", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "mta_bus_lines", "Maryland Transit Administration Summer 2020 Bus Routes", "rda", "data", TRUE, 2804L, NA, "2021-01-30", NA, "Baltimore area", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "mta_bus_stops", NA, "rda", "data", FALSE, 2804L, NA, NA, NA, "Baltimore area", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "ndc_projects", NA, "rda", "data", FALSE, 2804L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "neighborhoods", "Neighborhood boundaries for Baltimore City", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "neighborhoods_tracts", NA, "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "park_districts", NA, "rda", "data", TRUE, 2804L, NA, "2020-02-15", NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "parks", "Baltimore City Parks", "rda", "data", TRUE, 2804L, NA, "2021-01-26", NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "planning_districts", "Baltimore City Planning Districts", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "police_districts", "Baltimore City Police Districts", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "real_property", NA, "gpkg", "cachedata", FALSE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "request_types", "311 Service Request Types for Baltimore City", "rda", "data", TRUE, 2804L, 2020L, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "streets", "Baltimore City Street Center lines", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "trees", NA, "gpkg", "extdata", FALSE, 2804L, NA, "2020-02-15", NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "unimproved_property", NA, "gpkg", "extdata", FALSE, 2804L, NA, "2020-02-15", NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "vegetated_area", NA, "gpkg", "extdata", FALSE, 2804L, NA, "2020-02-15", NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "wards_1797_1918", "Historic Ward Boundaries, 1797-1918 for Baltimore City", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "zoning", "Baltimore City Zoning Code", "rda", "data", TRUE, 2804L, NA, NA, NA, "Baltimore City", NA, NA, NA, NA, NA, NA, NA, NA, NA,
  "md_food_stores_2017_2018", "Maryland Food Stores 2017-2018", NA, NA, NA, NA, 2018L, NA, NA, NA, NA, NA, "https://gis.mdfoodsystemmap.org/server/rest/services/FoodMapMD/MD_Food_Map_Services/MapServer/218/", "https://gis.mdfoodsystemmap.org/server/rest/services/FoodMapMD/MD_Food_Map_Services/MapServer/218/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "farmers_markets_2020", "Farmers Markets 2020", NA, NA, NA, NA, 2020L, NA, NA, NA, NA, NA, "https://gis.mdfoodsystemmap.org/server/rest/services/FoodMapMD/MD_Food_Map_Services/MapServer/481/", "https://gis.mdfoodsystemmap.org/server/rest/services/FoodMapMD/MD_Food_Map_Services/MapServer/481/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "baltimore_food_stores_2016", "Baltimore City Food Stores 2016", NA, NA, NA, NA, 2016L, NA, NA, NA, NA, NA, "https://gis.mdfoodsystemmap.org/server/rest/services/FoodMapMD/MD_Food_Map_Services/MapServer/217/", "https://gis.mdfoodsystemmap.org/server/rest/services/FoodMapMD/MD_Food_Map_Services/MapServer/217/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "baltimore_demolitions", "Completed City Demo", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "https://egisdata.baltimorecity.gov/egis/rest/services/Housing/DHCD_Open_Baltimore_Datasets/FeatureServer/0/", "https://egisdata.baltimorecity.gov/egis/rest/services/Housing/DHCD_Open_Baltimore_Datasets/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "contour_2ft", "Contour 2ft", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "https://egisdata.baltimorecity.gov/egis/rest/services/Housing/dmxBoundaries/MapServer/26/", "https://egisdata.baltimorecity.gov/egis/rest/services/Housing/dmxBoundaries/MapServer/26/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "contours_10ft", "Contours 10ft", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Contours_10ft/FeatureServer/0/", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Contours_10ft/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "open_vacant_building_notices", "Vacant Building Notices Open", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "https://egisdata.baltimorecity.gov/egis/rest/services/Housing/DHCD_Open_Baltimore_Datasets/FeatureServer/1/", "https://egisdata.baltimorecity.gov/egis/rest/services/Housing/DHCD_Open_Baltimore_Datasets/FeatureServer/1/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "liquor_licenses", "Liquor Licenses", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Liquor_Licenses/FeatureServer/0//", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Liquor_Licenses/FeatureServer/0//info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "fixed_speed_cameras", "Fixed Speed Cameras", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Fixed_Speed_Cameras/FeatureServer/0/", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Fixed_Speed_Cameras/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "red_light_cameras", "Red Light Cameras", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Red_Light_Cameras/FeatureServer/0/", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Red_Light_Cameras/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "hmt_2011", "2011_Housing_Market_Typology", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/2011_Housing_Market_Typology/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/2011_Housing_Market_Typology/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "hmt_2014", "2014_Housing_Market_Typology", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/2014_Housing_Market_Typology/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/2014_Housing_Market_Typology/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "service_calls_911_2021", "911_Calls_For_Service_2021", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/911_Calls_For_Service_2021/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/911_Calls_For_Service_2021/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "adult_day_care", "Adult_Day_Care", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Adult_Day_Care/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Adult_Day_Care/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "area_master_plan", "Area_Master_Plan", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Area_Master_Plan/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Area_Master_Plan/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "arrests_2017_2018", "Arrest_2018_2017", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Arrest_2018_2017/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Arrest_2018_2017/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "assisted_living_facility", "Assisted_Living_Facility", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Assisted_Living_Facility/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Assisted_Living_Facility/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "baltimore_city_line", "BaltCity_Line", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/BaltCity_Line/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/BaltCity_Line/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "bcpss_es_boundary", "BCPSS_Elementary_SchoolBoundary", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/BCPSS_Elementary_SchoolBoundary/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/BCPSS_Elementary_SchoolBoundary/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "bcpss_ms_boundary", "BCPSS_Middle_SchoolBoundary", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/BCPSS_Middle_SchoolBoundary/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/BCPSS_Middle_SchoolBoundary/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "bcpss_schools", "BCPSS_Schools", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/BCPSS_Schools/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/BCPSS_Schools/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "bike_lanes", "BikeFacilities_and_Bike_Lane", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/BikeFacilities_and_Bike_Lane/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/BikeFacilities_and_Bike_Lane/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "cctv_locations", "CCTV_Locations", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/CCTV_Locations/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/CCTV_Locations/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "chap_districts", "CHAP_Historic_District", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/CHAP_Historic_District/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/CHAP_Historic_District/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "cc_circulator_routes", "Charm_City_Circulator_Routes", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Charm_City_Circulator_Routes/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Charm_City_Circulator_Routes/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "cc_circulator_stops", "Charm_City_Circulator_Stops", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Charm_City_Circulator_Stops/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Charm_City_Circulator_Stops/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "code_red_cooling_center", "Code_Red_Cooling_Center", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Code_Red_Cooling_Center/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Code_Red_Cooling_Center/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "community_statistical_area", "Community_Statistical_Area", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Community_Statistical_Area/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Community_Statistical_Area/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "congressional_district", "Congressional_District", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Congressional_District/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Congressional_District/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "contours_10ft", "Contours_10ft", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Contours_10ft/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Contours_10ft/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "council_districts_2021", "Council_District_2021", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Council_District_2021/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Council_District_2021/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "courthouses", "Courthouses", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Courthouses/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Courthouses/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "crime_cameras", "Crime_Camera", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Crime_Camera/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Crime_Camera/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "critical_areas", "Critical_Area", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Critical_Area/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Critical_Area/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "dialysis_centers", "Dialysis_Center", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Dialysis_Center/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Dialysis_Center/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "enterprise_zones", "Enterprise_Zone", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Enterprise_Zone/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Enterprise_Zone/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "esri_opendata_police_customerservice311_2021_present", "ESRI_OpenData_police_CustomerService311_2021_Present", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/ESRI_OpenData_police_CustomerService311_2021_Present/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/ESRI_OpenData_police_CustomerService311_2021_Present/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "evacuation_shelters", "Evacuation_Shelter", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Evacuation_Shelter/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Evacuation_Shelter/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "farmers_markets", "Farmers_Market", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Farmers_Market/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Farmers_Market/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "fire_stations", "Fire_Station", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Fire_Station/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Fire_Station/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "fixed_speed_cameras", "Fixed_Speed_Cameras", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Fixed_Speed_Cameras/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Fixed_Speed_Cameras/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "floodplain", "Floodplain", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Floodplain/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Floodplain/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "food_desert", "Food_Desert", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Food_Desert/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Food_Desert/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "food_truck_locations", "Food_Truck_Locations", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Food_Truck_Locations/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Food_Truck_Locations/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "grocery_store_incentive_area", "Grocery_Store_Incentive_Area", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Grocery_Store_Incentive_Area/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Grocery_Store_Incentive_Area/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "grocery_store_renovation_incentive", "Grocery_Store_Renovation_Incentive", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Grocery_Store_Renovation_Incentive/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Grocery_Store_Renovation_Incentive/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "grocery_store", "Grocery_Store", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Grocery_Store/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Grocery_Store/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "healthy_food_priority_area", "Healthy_Food_Priority_Area", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Healthy_Food_Priority_Area/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Healthy_Food_Priority_Area/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "htc_applicants_prelim_approval_in_2010", "Historic_Tax_Credit_Applicants_Given_Preliminary_Approval_in_2010", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Historic_Tax_Credit_Applicants_Given_Preliminary_Approval_in_2010/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Historic_Tax_Credit_Applicants_Given_Preliminary_Approval_in_2010/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "homeless_shelters", "Homeless_Shelter", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Homeless_Shelter/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Homeless_Shelter/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "hospitals", "Hospitals", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Hospitals/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Hospitals/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "housing_market_typology_2017", "Housing_Market_Typology_2017", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Housing_Market_Typology_2017/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Housing_Market_Typology_2017/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "landmarks", "Landmarks", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Landmarks/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Landmarks/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "land_use", "LandUse", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/LandUse/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/LandUse/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "legislative_districts", "Legislative_Districts", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Legislative_Districts/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Legislative_Districts/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "libraries", "Library", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Library/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Library/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "liquor_license_tables_gdb", "Liquor_License_Tables_gdb", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Liquor_License_Tables_gdb/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Liquor_License_Tables_gdb/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "liquor_licenses", "Liquor_Licenses", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Liquor_Licenses/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Liquor_Licenses/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "medical_laboratories", "Medical_Laboratory", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Medical_Laboratory/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Medical_Laboratory/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "MIZOD", "MIZOD", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/MIZOD/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/MIZOD/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "monuments", "Monument", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Monument/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Monument/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "movie_theaters", "Movie_Theaters", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Movie_Theaters/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Movie_Theaters/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "multiuse_trails", "Multiuse_Trail", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Multiuse_Trail/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Multiuse_Trail/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "museums", "Museums", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Museums/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Museums/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "neighborhood_impact_investment_fund", "Neighborhood_Impact_Investment_Fund", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Neighborhood_Impact_Investment_Fund/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Neighborhood_Impact_Investment_Fund/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "neighborhoods", "Neighborhoods", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Neighborhoods/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Neighborhoods/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "nursing_home", "Nursing_Home", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Nursing_Home/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Nursing_Home/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "opportunity_zone", "Opportunity_Zone", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Opportunity_Zone/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Opportunity_Zone/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "parking_facilities", "Parking_Facilities", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Parking_Facilities/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Parking_Facilities/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "parks", "Parks", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Parks/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Parks/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "part1_crime_2014_2010", "Part1_Crime_2014_2010", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Part1_Crime_2014_2010/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Part1_Crime_2014_2010/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "part1_crime_2016_2015", "Part1_Crime_2016_2015", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Part1_Crime_2016_2015/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Part1_Crime_2016_2015/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "part1_crime_2020_2019", "Part1_Crime_2020_2019", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Part1_Crime_2020_2019/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Part1_Crime_2020_2019/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "part1_crime_2028_2017", "Part1_Crime_2028_2017", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Part1_Crime_2028_2017/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Part1_Crime_2028_2017/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "police_districts", "Police_Districts", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Police_Districts/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Police_Districts/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "police_posts", "Police_Posts", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Police_Posts/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Police_Posts/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "police_stations", "Police_Station", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Police_Station/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Police_Station/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "polling_places", "Polling_Place", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Polling_Place/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Polling_Place/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "private_schools", "Private_School", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Private_School/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Private_School/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "public_pools_baltimore_city", "Public_Pools_in_Baltimore_City", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Public_Pools_in_Baltimore_City/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Public_Pools_in_Baltimore_City/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "public_pools", "Public_Pools", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Public_Pools/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Public_Pools/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "recreation_centers", "Recreation_Center", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Recreation_Center/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Recreation_Center/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "red_light_cameras", "Red_Light_Cameras", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Red_Light_Cameras/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Red_Light_Cameras/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "religious_building", "Religious_Building", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Religious_Building/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Religious_Building/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "restaurants", "Restaurants", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Restaurants/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Restaurants/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "restricted_permit_parking", "Restricted_Permit_Parking", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Restricted_Permit_Parking/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Restricted_Permit_Parking/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "retail_incentive_area", "Retail_Incentive_Area", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Retail_Incentive_Area/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Retail_Incentive_Area/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "senior_centers", "Senior_Centers", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Senior_Centers/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Senior_Centers/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "streetcenterline", "StreetCenterLine", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/StreetCenterLine/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/StreetCenterLine/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "surface_water_quality_1995_2020", "SurfaceWaterQualityData1995through2020", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/SurfaceWaterQualityData1995through2020/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/SurfaceWaterQualityData1995through2020/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "trash_recycle_day", "Trash_Recycle_Day", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Trash_Recycle_Day/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Trash_Recycle_Day/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "universities", "University", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/University/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/University/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "urban_renewal_plan", "Urban_Renewal_Plan", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Urban_Renewal_Plan/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Urban_Renewal_Plan/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "vacants_to_value_distressed_market", "Vacants_to_Value_Distressed_Market", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Vacants_to_Value_Distressed_Market/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Vacants_to_Value_Distressed_Market/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "vacants_to_value_middle_market", "Vacants_to_Value_Middle_Market", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Vacants_to_Value_Middle_Market/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Vacants_to_Value_Middle_Market/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "vegetated_area", "Vegetated_Area", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Vegetated_Area/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Vegetated_Area/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "ward_precincts", "Ward_Precincts", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Ward_Precincts/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Ward_Precincts/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "water", "Water", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Water/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Water/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "zip_codes", "Zip_Code", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Zip_Code/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Zip_Code/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA,
  "zoning", "Zoning", NA, NA, FALSE, NA, NA, NA, NA, NA, NA, "Open Baltimore", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Zoning/FeatureServer/0", "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Zoning/FeatureServer/0/info/itemInfo?f=pjson", NA, NA, NA, NA, NA
)

data_index_layer_info <- data_index %>%
  filter(!is.na(layer_info), layer_maintainer == "Open Baltimore")

test_links <- as.list(
  "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/2011_Housing_Market_Typology/FeatureServer/0/info/itemInfo?f=pjson",
  "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/2014_Housing_Market_Typology/FeatureServer/0/info/itemInfo?f=pjson",
  "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/911_Calls_For_Service_2021/FeatureServer/0/info/itemInfo?f=pjson",
  "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Adult_Day_Care/FeatureServer/0/info/itemInfo?f=pjson",
  "https://opendata.baltimorecity.gov/egis/rest/services/Hosted/Area_Master_Plan/FeatureServer/0/info/itemInfo?f=pjson"
)


layer_info <- map(
  c(28:40),
  ~ esri2sf::esri2sf(url = data_index_layer_info$layer_url[.x], bbox = downtown_bbox)
)
# 26
esri2sf::esri2sf(url = "https://egisdata.baltimorecity.gov/egis/rest/services/Housing/dmxBoundaries/MapServer/26/", bbox = downtown_bbox)
data_index_test <- data_index %>%
  select(slug, date_updated)

data_index$datetime_updated <- as.Date(data_index$datetime_updated)

update_index_datetime <- function(index,
                                  slug,
                                  update = "datetime_updated",
                                  use_data = FALSE,
                                  overwrite = FALSE) {
  index[index$slug == slug, as.name(update)] <- Sys.time()

  if (use_data) {
    usethis::use_data(index, overwrite = overwrite)
  }

  return(index)
}

update_index_datetime(index = data_index, slug = "adopted_plans")
